name: Build, lint, and test

on: push

jobs:
    build:
        name: Build the Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Git repo
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Cache Node.js dependencies and Cypress
              id: node-cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      ~/.cache/Cypress
                  key: my-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - name: Install Node.js dependencies
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: yarn

            - name: Lint the application
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true
                  eslint_extensions: "js, jsx, ts, tsx"
                  prettier: true
                  prettier_extensions: "js, jsx, ts, tsx"
                  auto_fix: true
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build project
              run: yarn build

            - name: Build Storybook
              run: yarn build-storybook

    tests:
        name: Tests the Application
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Git repo
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Cache Node.js dependencies and Cypress
              id: node-cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      ~/.cache/Cypress
                  key: my-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  start: yarn start
                  wait-on: 'http://localhost:3000'
                  command: yarn test

            - name: Upload screenshots as artifacts
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

            - name: Upload videos as artifacts
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: cypress-videos
                  path: cypress/videos
